name: Pre-commit

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    paths:
      - '**.php'

jobs:
 testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: |-
          composer install

      - name: Run pint code-fixer
        run: |-
        ./vendor/bin/pint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply pint code-fixer changes
